### ISSUE TITLE
Remove mobile sub menu name and character name overflow

### ISSUE THREAD

**Issue by dm0896665** [Bentheburrito/sacastats#145]
![image](https://user-images.githubusercontent.com/46948300/210183271-322a53bc-cec7-4b4c-b4ae-dd9cadc91df9.png)
The hamburger button should always be on the right side. If the name is too long swap it for ellipses like so:
```css
#mobile-second-nav-header-name {
    width: 80%;
    overflow: hidden;
    text-overflow: ellipsis;
}
```
Same with the character name in the template
